# Generated by Django 4.2.11 on 2026-02-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hms_reception', '0008_appointment_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.IntegerField()),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hms_reception.appointment_details')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Morning', models.IntegerField(default=0)),
                ('Afternoon', models.IntegerField(default=0)),
                ('Night', models.IntegerField(default=0)),
                ('Instructions', models.CharField(blank=True, choices=[('After Food', 'After Food'), ('Before Food', 'Before Food'), ('Morning', 'Morning'), ('Night', 'Night')], max_length=255, null=True)),
                ('Prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='hms_doctor.prescription_details')),
            ],
        ),
    ]
