# Generated by Django 4.2.11 on 2026-02-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_pharmacy', '0001_initial'),
        ('hms_doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_details',
            name='Medicine_name',
        ),
        migrations.AddField(
            model_name='medicine_details',
            name='Medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hms_pharmacy.medicine_inventory'),
        ),
    ]
