# Generated by Django 4.2.11 on 2026-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_doctor', '0002_remove_medicine_details_medicine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription_details',
            name='Diagnosis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
