# Generated by Django 4.2.11 on 2026-02-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0009_rename_status_appointment_details_prescription_status_and_more'),
        ('hms_doctor', '0003_prescription_details_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_name', models.CharField(max_length=255)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Test_status', models.CharField(choices=[('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Assigned', max_length=20)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='hms_reception.appointment_details')),
            ],
        ),
    ]
