# Generated by Django 4.2.11 on 2026-02-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_doctor', '0004_test_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='Report_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
