# Generated by Django 4.2.11 on 2026-03-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0016_appointment_details_appointment_time'),
        ('hms_doctor', '0005_test_details_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_details',
            name='Appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='hms_reception.appointment_details'),
        ),
    ]
