# Generated by Django 4.2.11 on 2026-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_doctor', '0007_alter_prescription_details_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='Report_image',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
