# Generated by Django 4.2.11 on 2026-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_doctor', '0008_alter_test_details_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='Report_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
