# Generated by Django 4.2.11 on 2026-02-26 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hms_laboratory', '0001_initial'),
        ('hms_pharmacy', '0001_initial'),
        ('hms_reception', '0015_appointment_details_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='hms_reception.appointment_details')),
            ],
        ),
        migrations.CreateModel(
            name='BillTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name_snapshot', models.CharField(max_length=255)),
                ('test_price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='hms_billing.bill')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms_laboratory.test_master')),
            ],
        ),
        migrations.CreateModel(
            name='BillMedicineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name_snapshot', models.CharField(max_length=255)),
                ('price_per_piece_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('times_per_day', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_items', to='hms_billing.bill')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hms_pharmacy.medicine_inventory')),
            ],
        ),
    ]
