# Generated by Django 4.2.11 on 2026-02-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15),
        ),
    ]
