# Generated by Django 4.2.11 on 2026-01-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_details',
            name='Admin_name',
        ),
    ]
