# Generated by Django 4.2.11 on 2026-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0002_remove_admin_details_admin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_name', models.CharField(max_length=255)),
                ('Staff_id', models.IntegerField()),
                ('Staff_username', models.CharField(max_length=255)),
                ('Staff_password', models.CharField(max_length=255)),
                ('Staff_phone_no', models.BigIntegerField()),
                ('Staff_user_type', models.CharField(max_length=255)),
            ],
        ),
    ]
