# Generated by Django 4.2.11 on 2026-01-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0003_staff_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_details',
            name='Staff_id',
        ),
    ]
