# Generated by Django 4.2.11 on 2026-01-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0004_remove_staff_details_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=255)),
                ('Doctor_username', models.CharField(max_length=255)),
                ('Doctor_password', models.CharField(max_length=255)),
                ('Doctor_phone', models.BigIntegerField()),
                ('Doctor_department', models.CharField(max_length=255)),
            ],
        ),
    ]
