# Generated by Django 4.2.11 on 2026-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0005_doctor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_details',
            name='Staff_user_type',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Receptionist', 'Receptionist'), ('Pharmacy', 'Pharmacy'), ('Billing', 'Billing')], max_length=255),
        ),
    ]
