# Generated by Django 4.2.11 on 2026-01-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0007_doctor_details_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_details',
            name='availability_status',
        ),
    ]
