# Generated by Django 4.2.11 on 2026-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0009_doctor_details_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_details',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('On Leave', 'On Leave')], default='Available', max_length=255),
        ),
    ]
