# Generated by Django 4.2.11 on 2026-02-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0011_alter_doctor_details_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_details',
            name='Doctor_department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('General Medicine', 'General Medicine')], max_length=255),
        ),
    ]
