# Generated by Django 4.2.11 on 2026-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=255)),
                ('Patient_age', models.IntegerField()),
                ('Patient_phone', models.BigIntegerField()),
                ('Patient_address', models.CharField(max_length=255)),
                ('Doctor_name', models.CharField(max_length=255)),
            ],
        ),
    ]
