# Generated by Django 4.2.11 on 2026-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='Patient_gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='Patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='Patient_phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
