# Generated by Django 4.2.11 on 2026-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0002_patient_details_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='Patient_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='Patient_gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='Patient_phone',
            field=models.BigIntegerField(),
        ),
    ]
