# Generated by Django 4.2.11 on 2026-02-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0003_alter_patient_details_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='Patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=255),
        ),
    ]
