# Generated by Django 4.2.11 on 2026-02-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0004_alter_patient_details_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_details',
            name='Doctor_name',
        ),
    ]
