# Generated by Django 4.2.11 on 2026-02-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0012_alter_doctor_details_doctor_department'),
        ('hms_reception', '0005_remove_patient_details_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appintment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('token_number', models.IntegerField()),
                ('doctorData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_admin.doctor_details')),
                ('patientData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_reception.patient_details')),
            ],
        ),
    ]
