# Generated by Django 4.2.11 on 2026-02-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0012_alter_doctor_details_doctor_department'),
        ('hms_reception', '0006_appintment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Token_number', models.IntegerField()),
                ('DoctorData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_admin.doctor_details')),
                ('PatientData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_reception.patient_details')),
            ],
        ),
        migrations.DeleteModel(
            name='Appintment_details',
        ),
    ]
