# Generated by Django 4.2.11 on 2026-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0007_appointment_details_delete_appintment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_details',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
