# Generated by Django 4.2.11 on 2026-02-12 07:43

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0008_appointment_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_details',
            name='Created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now
            ),
            preserve_default=False,
        ),
    ]