# Generated by Django 4.2.11 on 2026-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0008_appointment_details_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_details',
            old_name='Status',
            new_name='Prescription_status',
        ),
        migrations.AddField(
            model_name='appointment_details',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
