# Generated by Django 4.2.11 on 2026-02-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0009_rename_status_appointment_details_prescription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_details',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
