# Generated by Django 4.2.11 on 2026-02-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0010_alter_appointment_details_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_details',
            name='Created_at',
        ),
    ]
