# Generated by Django 4.2.11 on 2026-02-12 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0011_remove_appointment_details_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_details',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
