# Generated by Django 4.2.11 on 2026-02-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0012_appointment_details_created_at'),
    ]

    operations = [
    ]
