# Generated by Django 4.2.11 on 2026-02-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0013_auto_20260212_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_details',
            name='Created_at',
        ),
    ]
