# Generated by Django 4.2.11 on 2026-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_reception', '0015_appointment_details_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_details',
            name='Appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
