# Generated by Django 4.2.11 on 2026-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_name', models.CharField(max_length=100, unique=True)),
                ('Medicine_price', models.FloatField(max_length=10)),
                ('Stock', models.IntegerField(choices=[(1, 'In Stock'), (0, 'Out of Stock')], default=1)),
            ],
        ),
    ]
