# Generated by Django 4.2.11 on 2026-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_inventory',
            name='Medicine_price',
            field=models.FloatField(),
        ),
    ]
